version: '3.9'

services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: cartrita_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # We map the host port 5434 to the container's port 5432.
      # This prevents conflicts with any locally installed PostgreSQL instance.
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: cartrita_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # The backend service connects to the db service internally on port 5432
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  postgres_data:

