services:
  db:
    # --- FIX: Build our custom image instead of pulling one ---
    build:
      context: ./postgres-custom
    container_name: cartrita_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432'
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cartrita-net

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile # Correct path to backend Dockerfile
    container_name: cartrita_backend
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cartrita-net

networks:
  cartrita-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local