services:
  # PostgreSQL Database with pgvector
  db:
    image: pgvector/pgvector:pg16
    container_name: cartrita-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: robert
      POSTGRES_PASSWORD: punky1
      POSTGRES_DB: dat-bitch-cartrita
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - cartrita-network-dev
    command: >
      postgres
      -c shared_preload_libraries=vector
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=on
      -c log_min_messages=info

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: cartrita-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data
    networks:
      - cartrita-network-dev
    command: redis-server --appendonly yes

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  cartrita-network-dev:
    driver: bridge
