version: '3.9'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: cartrita-db-new
    restart: unless-stopped
    environment:
      POSTGRES_USER: robert
      POSTGRES_PASSWORD: punky1
      POSTGRES_DB: dat-bitch-cartrita
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - cartrita-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U robert -d dat-bitch-cartrita']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cartrita-redis-new
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - cartrita-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.0
    container_name: cartrita-otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yml"]
    environment:
      OTEL_EXPORTER_OTLP_HTTP_ENDPOINT: "${OTEL_EXPORTER_OTLP_HTTP_ENDPOINT:-}"
      OTEL_EXPORTER_OTLP_HEADERS: "${OTEL_EXPORTER_OTLP_HEADERS:-}"
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - '4317:4317'
      - '4318:4318'
      - '8889:8889'
      - '13133:13133'
      - '1777:1777'
      - '55679:55679'
    networks:
      - cartrita-network
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:13133/ || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./packages/cartrita-v2
      dockerfile: Dockerfile
    container_name: cartrita-v2-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=8001
      - ENABLE_TELEMETRY=false
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - POSTGRES_USER=robert
      - POSTGRES_PASSWORD=punky1
      - POSTGRES_DB=dat-bitch-cartrita
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://robert:punky1@postgres:5432/dat-bitch-cartrita
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    env_file:
      - packages/cartrita-v2/.env
    ports:
      - '8001:8001'
    volumes:
      - ./packages/cartrita-v2:/usr/src/app
      - ./packages/cartrita-v2/uploads:/usr/src/app/uploads
      - ./packages/cartrita-v2/logs:/usr/src/app/logs
      - /usr/src/app/node_modules
    networks:
      - cartrita-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:8001/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  cartrita-network:
    driver: bridge
