apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    name: ${NAMESPACE}
    environment: ${ENVIRONMENT}
    app: cartrita
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cartrita-config
  namespace: ${NAMESPACE}
data:
  NODE_ENV: "${ENVIRONMENT}"
  PORT: "3000"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=cartrita-backend,service.version=${BUILD_VERSION:-latest},environment=${ENVIRONMENT}"
---
apiVersion: v1
kind: Secret
metadata:
  name: cartrita-secrets
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DATABASE_URL: "${DATABASE_URL}"
  REDIS_URL: "${REDIS_URL}"
  JWT_SECRET: "${JWT_SECRET}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  HUGGINGFACE_API_KEY: "${HUGGINGFACE_API_KEY}"
  DEEPGRAM_API_KEY: "${DEEPGRAM_API_KEY}"
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
  GROQ_API_KEY: "${GROQ_API_KEY}"
  REPLICATE_API_KEY: "${REPLICATE_API_KEY}"
  LANGCHAIN_API_KEY: "${LANGCHAIN_API_KEY}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cartrita-uploads
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cartrita-logs
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
