# OpenTelemetry Collector configuration for Cartrita MCP
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'cartrita'
          static_configs:
            - targets: ['localhost:8889']

processors:
  resource:
    attributes:
      - key: service.namespace
        value: cartrita
        action: upsert
      - key: deployment.environment
        value: production
        action: upsert
  batch:
    timeout: 1s
    send_batch_size: 512
    send_batch_max_size: 1024

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: cartrita
  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [logging]
    metrics:
      receivers: [otlp, prometheus]
      processors: [resource, batch]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [logging]
  extensions: [health_check, pprof, zpages]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777
  
  zpages:
    endpoint: 0.0.0.0:55679