# Cartrita V2 Multi-Agent OS - Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'cartrita-v2'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Cartrita Backend V2
  - job_name: 'cartrita-backend-v2'
    static_configs:
      - targets: ['backend-v2:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # RAG Service
  - job_name: 'cartrita-rag'
    static_configs:
      - targets: ['rag-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Python FAISS Service
  - job_name: 'cartrita-faiss'
    static_configs:
      - targets: ['faiss-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Worker Services
  - job_name: 'cartrita-worker'
    static_configs:
      - targets: ['worker:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  # Legacy Backend (if still running)
  - job_name: 'cartrita-backend-legacy'
    static_configs:
      - targets: ['backend:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL metrics (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Elasticsearch metrics (if available)
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom application metrics
  - job_name: 'cartrita-custom'
    static_configs:
      - targets: ['backend-v2:8001']
    metrics_path: '/api/metrics/custom'
    scrape_interval: 60s
    honor_labels: true
    scrape_timeout: 30s