# Prometheus configuration for Cartrita MCP
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'cartrita-mcp'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rules for alerting
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  # MCP Orchestrator
  - job_name: 'mcp-orchestrator'
    static_configs:
      - targets: ['mcp-orchestrator:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Intelligence Supervisor
  - job_name: 'mcp-intelligence'
    static_configs:
      - targets: ['mcp-supervisor-intelligence:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Multi-Modal Supervisor
  - job_name: 'mcp-multimodal'
    static_configs:
      - targets: ['mcp-supervisor-multimodal:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # System Supervisor
  - job_name: 'mcp-system'
    static_configs:
      - targets: ['mcp-supervisor-system:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Legacy Backend
  - job_name: 'cartrita-backend'
    static_configs:
      - targets: ['backend:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL metrics (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
    metrics_path: /metrics