import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChunkErrorDiagnostic } from "../components/ChunkErrorDiagnostic";
import { FontLoadOptimizer } from "../components/FontLoadOptimizer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // Optimizes font loading
  preload: true, // Explicitly enable preloading
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap", // Optimizes font loading
  preload: true, // Explicitly enable preloading
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
        suppressHydrationWarning={true}
      >
        <FontLoadOptimizer />
        {children}
        <ChunkErrorDiagnostic />
      </body>
    </html>
  );
}
