name: security-secret-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python (for detect-secrets)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Run detect-secrets (baseline if present)
        run: |
          if [ -f .secrets.baseline ]; then
            echo "Using existing baseline";
            detect-secrets scan --baseline .secrets.baseline || (echo "Potential new secrets detected" && exit 1);
          else
            echo "No baseline found; generating ephemeral scan";
            detect-secrets scan > /tmp/ds.scan || true;
            echo "Ephemeral scan created (not failing build without baseline).";
          fi

      - name: Install gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks

      - name: Run gitleaks scan
        run: |
          ./gitleaks detect --no-banner --report-format sarif --report-path gitleaks.sarif || (echo "Gitleaks found issues" && exit 1)

      - name: Upload SARIF (gitleaks)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
